[package]
name = "swbuf"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Cross-platform software buffer"
documentation = "https://docs.rs/swbuf"
readme = "README.md"
repository = "https://github.com/rust-windowing/swbuf"
keywords = ["framebuffer", "windowing"]
categories = ["game-development", "graphics", "gui", "multimedia", "rendering"]
exclude = ["examples"]

[dependencies]
thiserror = "1.0.30"
raw-window-handle = "0.5.0"

[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
nix = "0.26.1"
wayland-backend = {version = "0.1.0-beta.14", features = ["client_system"]}
wayland-client = {version = "0.30.0-beta.14"}
x11-dl = "2.19.1"

[target.'cfg(target_os = "windows")'.dependencies.windows-sys]
version = "0.42.0"
features = ["Win32_Graphics_Gdi", "Win32_UI_WindowsAndMessaging", "Win32_Foundation"]

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24.0"
core-graphics = "0.22.3"
foreign-types = "0.3.0"
objc = "0.2.7"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.78"

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.55"
features = ["CanvasRenderingContext2d", "Document", "Element", "HtmlCanvasElement", "ImageData", "Window"]

[target.'cfg(target_os = "redox")'.dependencies]
redox_syscall = "0.3"

[dev-dependencies]
instant = "0.1.12"
winit = "0.27.2"

[dev-dependencies.image]
version = "0.23.14"
# Disable rayon on web
default-features = false
features = ["jpeg"]

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
# Turn rayon back on everywhere else; creating the separate entry resets the features to default.
image = "0.23.14"
rayon = "1.5.1"
